#!/usr/bin/env bash

if [ "$#" -eq 0 ] ; then
    echo "Expected host:path" >&2
    exit -1
fi

set -u
set -e

X="$1"
shift 1
arr=(`echo $X | tr ':' ' '`)

dest=${arr[0]}
remote_path=${arr[1]}

if [ -z "$dest" ] ; then
    echo "Destination not specified" >&2
    exit -1
fi

if [ -z "$remote_path" ] ; then
    echo "Path on destination not specified" >&2
    exit -1
fi

branch=master

git-bottle
version=`git rev-parse HEAD`
git-unbottle

git push "$@" -f ${dest}:${remote_path} ${version}:${branch}
ssh -t ${dest} "cd ${remote_path} && git reset --hard ${branch}"
