#!/bin/bash

# Continue a rebase, `am`, a cherry-pick or a revert, depending on the situation.

if [[ -e .git/CHERRY_PICK_HEAD ]] ; then
    exec git cherry-pick --continue "$@"
elif [[ -e .git/REVERT_HEAD ]] ; then
    exec git revert --continue "$@"
elif [[ -e .git/rebase-apply/applying ]] ; then
    exec git am --continue "$@"
elif [[ -e .git/rebase-apply ]] ; then
    exec git rebase --continue "$@"
elif [[ -e .git/rebase-merge ]] ; then
    exec git rebase --continue "$@"
else
    echo git-continue: unknown state
    exit -1
fi
