#!/usr/bin/env bash

#
# Set my per-repository credentials using dirlocalenv.
#
# See: https://github.com/da-x/dirlocalenv
#

set -e

dirname=$(basename $(pwd))
email=$(dirlocalenv bash -c 'echo $EMAIL_SPHERE')
git config user.email ${email}
