#!/usr/bin/env bash

set -e

dirname=$(basename $(realpath $(pwd)))

git init
git-set-email
git add .

if [[ "$(git status --porcelain | wc -l)" == "0" ]] ; then
    touch  .gitignore
    git add .
fi

git commit -a -m "Initial commit for \`$dirname\`"
