#!/bin/bash

# Skip a patch in a rebase or am, depending on the situation.

if [[ -e .git/rebase-apply/applying ]] ; then
    exec git am --skip "$@"
elif [[ -e .git/rebase-apply ]] ; then
    exec git rebase --skip "$@"
elif [[ -e .git/rebase-merge ]] ; then
    exec git rebase --skip "$@"
else
    echo git-continue: unknown state
    exit -1
fi
