#!/bin/bash -ue

cur_tree() {
    git show --format="%T" -s
}

# Prepare commit
orig_pwd=`pwd`
tree=`cur_tree`
git commit -m "TEMP-COMMIT: staged" --allow-empty
if [ "${tree}" == "`cur_tree`" ] ; then
    git reset --soft HEAD^
fi

tree=`cur_tree`
git commit -a -m "TEMP-COMMIT: uncommitted" --allow-empty
if [ "${tree}" == "`cur_tree`" ] ; then
    git reset --soft HEAD^
fi

tree=`cur_tree`
git add -A .
git commit -m "TEMP-COMMIT: untracked" --allow-empty
if [ "${tree}" == "`cur_tree`" ] ; then
    git reset --soft HEAD^
fi
