#!/usr/bin/env python

"""
For files that are "deleted-by-them", show the changes between
the deleted version (older) and their modified version (newer).

The interface of this script is tentative.
"""

import os
import sys

files = []
for line in os.popen("git status --porcelain").readlines():
    state, filename = line.split(' ', 1)
    if state == "UD":
        files.append(filename.strip())

git_original_rev = os.popen("git-original-rev").read().strip()
if len(sys.argv) == 1:
    print git_original_rev + "~1..HEAD"
    sys.exit(0)
cmd = ["git", sys.argv[1],  git_original_rev + "~1..HEAD"] + sys.argv[2:] + files
os.execvp("git", cmd)
