#!/usr/bin/env python

"""
For files that are "deleted-by-them", show the changes between
the deleted version (older) and their modified version (newer).

The interface of this script is tentative.
"""

import os
import sys

files = []
for line in os.popen("git status --porcelain").readlines():
    state, filename = line.split(' ', 1)
    if state == "DU":
        files.append(filename.strip())

git_original_rev = os.popen("git-original-rev").read().strip()
cmd = ["git", "show", git_original_rev] + sys.argv[2:] + files
os.execvp("git", cmd)
